/**
 * Shared helpers and constants for E2E tests
 *
 * In MOCK_MODE (default), the useGitHub hook generates data client-side.
 * No API route interception is needed. The hook provides:
 * - User: dev-user / Alex Developer
 * - 87 repos across 3 pages (30 per page)
 * - Repos: fintech-dashboard, ai-analytics-platform, react-component-library, etc.
 */

// The mock user set by useGitHub in MOCK_MODE
export const MOCK_USER = {
  login: 'dev-user',
  name: 'Alex Developer'
}

// First page repo names (generated by useGitHub's generateMockData)
export const FIRST_PAGE_REPOS = [
  'fintech-dashboard',
  'ai-analytics-platform',
  'react-component-library',
  'serverless-api-gateway',
  'mobile-app-flutter',
  'kubernetes-deploy-scripts',
  'blockchain-wallet-core',
  'e-commerce-microservices',
  'docs-portal',
  'auth-service',
  'data-lake-processor',
  'ios-checkout-sdk',
  'android-pos-terminal',
  'graphql-federation',
  'legacy-crm-importer',
  'design-system-tokens',
  'devops-ci-templates',
  'nlp-chatbot-engine',
  'web-assembly-video-editor',
  'marketing-landing-pages'
]

// A public, non-fork repo for testing quick actions
export const SAMPLE_PUBLIC_REPO = 'ai-analytics-platform'

// A private repo for filter testing (i % 3 === 0)
export const SAMPLE_PRIVATE_REPO = 'fintech-dashboard'
