// SPDX-License-Identifier: AGPL-3.0-only
/**
 * First-run bootstrap for local/desktop installs (Windows package + any
 * self-host that wants a zero-config first launch).
 *
 * Production boot hard-aborts without strong SESSION_SECRET / WEBHOOK_SECRET /
 * CREDENTIAL_ENCRYPTION_KEY (server/lib/startup-secrets-check.js) and
 * API_KEY_SECRET (server/index.js) — correctly, for a hosted deployment. But a
 * double-clicked desktop app has no operator to hand-write a .env before first
 * launch, so this script generates one with strong random secrets the moment
 * it's missing. It never touches an existing .env — self-hosters who already
 * configured one keep full control.
 *
 * No dependencies beyond Node built-ins (crypto/fs/path/url) — this must run
 * standalone from a packaged installer before `npm install` guarantees
 * anything is on disk.
 */
import { randomBytes } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

function generateSecret() {
    // 48 random bytes -> 64 base64url chars; well over every min-length gate
    // in startup-secrets-check.js (32 bytes) with no padding/URL-unsafe chars.
    return randomBytes(48).toString('base64url');
}

/**
 * Generate a boot-viable .env at `envPath` if (and only if) it does not
 * already exist. Idempotent: an existing .env is never modified.
 *
 * The existence check and the write are deliberately not two separate
 * steps — that shape (existsSync, then a later writeFileSync) is a
 * check-then-act race: another launch of the same packaged app, or a
 * concurrent install, could create the file in the gap between the check
 * and the write. Instead the write itself is the check: `flag: 'wx'` asks
 * the OS to create-and-open the file exclusively, failing atomically with
 * an EEXIST error if the path already exists — caught below and treated
 * exactly like the old "already exists" fast path.
 *
 * @param {object} [opts]
 * @param {string} [opts.envPath] - target .env path (default: repo root .env)
 * @param {string} [opts.dataDir] - if given, written as DATA_DIR
 * @returns {{ created: boolean, envPath: string }}
 */
export function ensureFirstRunEnv({ envPath, dataDir } = {}) {
    const targetPath = envPath ? path.resolve(envPath) : path.join(REPO_ROOT, '.env');

    const lines = [
        '# Generated by scripts/first-run.mjs for a local/desktop install.',
        '# Safe to edit. WARNING: do NOT delete this file on an install you care',
        '# about — CREDENTIAL_ENCRYPTION_KEY below encrypts every credential you',
        '# save in the app (Azure PATs, AI keys); regenerated secrets cannot',
        '# decrypt them.',
        '',
        'NODE_ENV=production',
        // Loopback-only so the Windows Firewall prompt never appears and the
        // server is never LAN-exposed by default (see server/config.js `host`).
        'HOST=127.0.0.1',
        'PORT=3001',
        `SESSION_SECRET=${generateSecret()}`,
        `WEBHOOK_SECRET=${generateSecret()}`,
        `CREDENTIAL_ENCRYPTION_KEY=${generateSecret()}`,
        `API_KEY_SECRET=${generateSecret()}`,
        // Single-user/local install: there is no one else to email, and
        // license-key/retention notices just log instead of hard-aborting boot.
        'ALLOW_CONSOLE_EMAIL=true',
    ];

    if (dataDir) {
        lines.push(`DATA_DIR=${dataDir}`);
    }

    try {
        // The target may live in a directory that doesn't exist yet (the
        // Windows package now keeps .env in the DATA dir, created here on
        // the very first launch before the server ever runs).
        mkdirSync(path.dirname(targetPath), { recursive: true });
        writeFileSync(targetPath, lines.join('\n') + '\n', {
            encoding: 'utf8',
            mode: 0o600,
            // Exclusive create: atomically fails with EEXIST rather than
            // truncating/overwriting if the path already exists — see the
            // check-then-act note above.
            flag: 'wx',
        });
        return { created: true, envPath: targetPath };
    } catch (err) {
        if (err.code === 'EEXIST') {
            return { created: false, envPath: targetPath };
        }
        throw err;
    }
}

/**
 * Persist the port a launcher actually bound to into the .env it loads.
 *
 * The Windows launcher scans for a free port when the configured one is taken.
 * Recording the winner only in the per-run `.grm.port` marker left `.env`
 * holding the old PORT, so the scan re-ran on every launch and could land
 * somewhere new each day — while the OAuth callback registered at GitHub still
 * pointed at the original port. The login then dead-ends on GitHub's
 * redirect_uri mismatch page, and re-registering the callback fixes it only
 * until the next launch. Writing the winner back makes the port stable, so
 * registering the callback once is enough.
 *
 * Reuses server/lib/env-file.js's `updateEnvFile` (allowlisted key, atomic
 * temp-file+rename, mode 0600) rather than a second .env writer: this file
 * holds CREDENTIAL_ENCRYPTION_KEY, and a truncating write would strand every
 * encrypted credential in the database. The import is dynamic so the
 * dependency-free bootstrap path above still runs in a tree where server/ is
 * absent.
 *
 * @param {object} opts
 * @param {string} [opts.envPath] - target .env (default: GRM_ENV_FILE / repo root)
 * @param {string|number} opts.port
 * @returns {Promise<{ envPath: string, created: boolean }>}
 */
export async function persistPort({ envPath, port }) {
    const parsed = Number(port);
    if (!Number.isInteger(parsed) || parsed < 1 || parsed > 65535) {
        throw new Error(`[first-run] refusing to persist an invalid PORT: ${port}`);
    }
    const { updateEnvFile } = await import('../server/lib/env-file.js');
    return updateEnvFile({ PORT: String(parsed) }, { envPath });
}

function parseCliArgs(argv) {
    let envPath;
    let dataDir;
    let setPort;
    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === '--data-dir') {
            dataDir = argv[++i];
        } else if (arg === '--set-port') {
            setPort = argv[++i];
        } else if (!arg.startsWith('--') && envPath === undefined) {
            envPath = arg;
        }
    }
    return { envPath, dataDir, setPort };
}

const isMainModule = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMainModule) {
    const { envPath, dataDir, setPort } = parseCliArgs(process.argv.slice(2));
    if (setPort !== undefined) {
        const written = await persistPort({ envPath, port: setPort });
        process.stdout.write(`[first-run] PORT=${setPort} persisted to ${written.envPath}\n`);
    } else {
        const result = ensureFirstRunEnv({ envPath, dataDir });
        // Idempotent re-runs must stay quiet — this fires on every launch of a
        // packaged app, and an existing .env means there is nothing to report.
        if (result.created) {
            process.stdout.write(`[first-run] generated ${result.envPath}\n`);
        }
    }
}
