// SPDX-License-Identifier: AGPL-3.0-only
/**
 * First-run bootstrap for local/desktop installs (Windows package + any
 * self-host that wants a zero-config first launch).
 *
 * Production boot hard-aborts without strong SESSION_SECRET / WEBHOOK_SECRET /
 * CREDENTIAL_ENCRYPTION_KEY (server/lib/startup-secrets-check.js) and
 * API_KEY_SECRET (server/index.js) — correctly, for a hosted deployment. But a
 * double-clicked desktop app has no operator to hand-write a .env before first
 * launch, so this script generates one with strong random secrets the moment
 * it's missing. It never touches an existing .env — self-hosters who already
 * configured one keep full control.
 *
 * No dependencies beyond Node built-ins (crypto/fs/path/url) — this must run
 * standalone from a packaged installer before `npm install` guarantees
 * anything is on disk.
 */
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

function generateSecret() {
    // 48 random bytes -> 64 base64url chars; well over every min-length gate
    // in startup-secrets-check.js (32 bytes) with no padding/URL-unsafe chars.
    return randomBytes(48).toString('base64url');
}

/**
 * Generate a boot-viable .env at `envPath` if (and only if) it does not
 * already exist. Idempotent: an existing .env is never modified.
 *
 * @param {object} [opts]
 * @param {string} [opts.envPath] - target .env path (default: repo root .env)
 * @param {string} [opts.dataDir] - if given, written as DATA_DIR
 * @returns {{ created: boolean, envPath: string }}
 */
export function ensureFirstRunEnv({ envPath, dataDir } = {}) {
    const targetPath = envPath ? path.resolve(envPath) : path.join(REPO_ROOT, '.env');

    if (existsSync(targetPath)) {
        return { created: false, envPath: targetPath };
    }

    const lines = [
        '# Generated by scripts/first-run.mjs for a local/desktop install.',
        '# Safe to edit. Delete this file and relaunch to regenerate fresh secrets.',
        '',
        'NODE_ENV=production',
        // Loopback-only so the Windows Firewall prompt never appears and the
        // server is never LAN-exposed by default (see server/config.js `host`).
        'HOST=127.0.0.1',
        'PORT=3001',
        `SESSION_SECRET=${generateSecret()}`,
        `WEBHOOK_SECRET=${generateSecret()}`,
        `CREDENTIAL_ENCRYPTION_KEY=${generateSecret()}`,
        `API_KEY_SECRET=${generateSecret()}`,
        // Single-user/local install: there is no one else to email, and
        // license-key/retention notices just log instead of hard-aborting boot.
        'ALLOW_CONSOLE_EMAIL=true',
    ];

    if (dataDir) {
        lines.push(`DATA_DIR=${dataDir}`);
    }

    writeFileSync(targetPath, lines.join('\n') + '\n', { encoding: 'utf8', mode: 0o600 });
    return { created: true, envPath: targetPath };
}

function parseCliArgs(argv) {
    let envPath;
    let dataDir;
    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === '--data-dir') {
            dataDir = argv[++i];
        } else if (!arg.startsWith('--') && envPath === undefined) {
            envPath = arg;
        }
    }
    return { envPath, dataDir };
}

const isMainModule = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMainModule) {
    const { envPath, dataDir } = parseCliArgs(process.argv.slice(2));
    const result = ensureFirstRunEnv({ envPath, dataDir });
    // Idempotent re-runs must stay quiet — this fires on every launch of a
    // packaged app, and an existing .env means there is nothing to report.
    if (result.created) {
        process.stdout.write(`[first-run] generated ${result.envPath}\n`);
    }
}
