#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2025-2026 Bola Labs. All rights reserved.
/*
 * Generates every RepoManager brand asset from one geometry definition.
 *
 * The mark is never redrawn by hand. Each surface (favicon, Windows .ico slot,
 * macOS tile, social card) is emitted from the constants below, so a change to
 * the mark propagates everywhere instead of leaving one stale copy behind — the
 * failure mode the previous logo had, where public/logo.svg and the installer's
 * icon had drifted into two different marks.
 *
 *   node scripts/gen-brand.mjs            → write brand/ + public/ SVGs
 *   node scripts/gen-brand.mjs --check    → verify on-disk files match (CI gate)
 *
 * Rasters (.png, .ico) are produced by scripts/gen-brand-raster.mjs, which needs
 * Playwright; this file has no dependencies so the gate can run anywhere.
 *
 * Spec: docs/BRAND.md
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

// ── Palette — inherited from the BolaLabs platform, not re-picked ──────────
// bolalabs-platform/index.css @theme. The lime is fill-only; never set as text.
export const COLOR = {
  lime: '#7fc528',   // primary-500 — the attending node, the one brand carrier
  ink: '#0f172a',   // slate-900 — structure on light grounds
  paper: '#f8fafc',   // slate-50  — structure on dark grounds
  ground: '#020617',   // slate-950 — tile ground
}

// ── Geometry — a 32-unit grid ─────────────────────────────────────────────
//
// Both cuts are composed so the INK is centred on (16,16) and fills ~74% of the
// box. That is not cosmetic: the first draft put the rail at x=10 and let the
// ring run to x=29.5, which centred the ink on 19.1 — nearly three units right
// of the box. Rendered as a bare mark it read as a small glyph pushed against
// the right edge with a hole on the left. Centring is done on the ink bounds,
// then nudged so the visually heavy node does not drag the composition right.
const DISPLAY = {
  stroke: 2.9,
  rail: 'M5.8 5.6 V26.4',
  stub: 'M5.8 16 H14.4',
  terminals: [[5.8, 5.6], [5.8, 26.4]],
  terminalR: 2.1,
  node: [20.3, 16], nodeR: 4.7,
  ringR: 7.6, ringStroke: 1.9, ringOpacity: 0.45,
}

// Small cut — 24 px and below. The ring closes into a smudge at that size and
// a 2.9 stroke lands between pixels, so it is redrawn rather than scaled:
// ring dropped, node grown, strokes thickened, terminals absorbed by the caps.
const SMALL = {
  stroke: 3.8,
  rail: 'M6.5 6.5 V25.5',
  stub: 'M6.5 16 H13.5',
  node: [21, 16], nodeR: 6.2,
}

const NOTE = (what) =>
  `<!-- RepoManager — ${what}. Generated by scripts/gen-brand.mjs; do not edit by hand. Spec: docs/BRAND.md -->`

function markBody(cut, structure, accent) {
  const g = cut === 'small' ? SMALL : DISPLAY
  const parts = [
    `<g fill="none" stroke="${structure}" stroke-width="${g.stroke}" stroke-linecap="round">`,
    `<path d="${g.rail}"/><path d="${g.stub}"/>`,
    `</g>`,
  ]
  if (g.terminals) {
    for (const [cx, cy] of g.terminals) {
      parts.push(`<circle cx="${cx}" cy="${cy}" r="${g.terminalR}" fill="${structure}"/>`)
    }
  }
  parts.push(`<circle cx="${g.node[0]}" cy="${g.node[1]}" r="${g.nodeR}" fill="${accent}"/>`)
  if (g.ringR) {
    parts.push(
      `<circle cx="${g.node[0]}" cy="${g.node[1]}" r="${g.ringR}" fill="none" ` +
      `stroke="${accent}" stroke-width="${g.ringStroke}" opacity="${g.ringOpacity}"/>`
    )
  }
  return parts.join('\n  ')
}

function mark({ cut = 'display', structure = COLOR.ink, accent = COLOR.lime, label }) {
  return `${NOTE(label)}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32"
     role="img" aria-label="RepoManager">
  ${markBody(cut, structure, accent)}
</svg>
`
}

/**
 * A tile: the mark on the brand ground.
 *
 * `size` is the artboard; `art` is how much of it the mark occupies; `radius`
 * is the corner. macOS is the odd one out — it wants art at 824 inside a 1024
 * canvas with a 185.4 radius, and unlike iOS it does NOT round the corners for
 * you, so the shape has to be in the file.
 */
function tile({ size, art, radius, label, cut = 'display', markScale = 0.72 }) {
  const inset = (size - art) / 2
  // The mark occupies `markScale` of the ground, centred — it does NOT fill it.
  // On an adaptive (circular-masked) icon a mark drawn edge to edge loses its
  // corners; on macOS a mark without padding reads as oversized next to every
  // other icon in the Dock, which all share Apple's optical inset.
  const markSize = art * markScale
  const pad = inset + (art - markSize) / 2
  const scale = markSize / 32
  return `${NOTE(label)}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}"
     width="${size}" height="${size}" role="img" aria-label="RepoManager">
  <rect x="${inset}" y="${inset}" width="${art}" height="${art}" rx="${radius}" fill="${COLOR.ground}"/>
  <g transform="translate(${round(pad)} ${round(pad)}) scale(${round(scale)})">
  ${markBody(cut, COLOR.paper, COLOR.lime)}
  </g>
</svg>
`
}

const round = (n) => Number(n.toFixed(6))

/**
 * Horizontal lockup: mark + wordmark.
 *
 * The wordmark is live <text> in Archivo, NOT outlines — this repository has no
 * font-outlining tool, and shipping a wrong-metrics fake would be worse than a
 * documented fallback. Anywhere Archivo is unavailable it degrades to the
 * system grotesque. For print or a third party, export this to outlines first.
 */
function lockup({ stacked = false, structure = COLOR.ink }) {
  const label = stacked ? 'stacked lockup' : 'horizontal lockup'
  if (stacked) {
    return `${NOTE(label)}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 96" width="160" height="96"
     role="img" aria-label="RepoManager">
  <g transform="translate(64 4) scale(1)">
  ${markBody('display', structure, COLOR.lime)}
  </g>
  <text x="80" y="76" text-anchor="middle"
        font-family="Archivo, 'Archivo Variable', ui-sans-serif, system-ui, sans-serif"
        font-size="21" font-weight="700" letter-spacing="-0.5" fill="${structure}">RepoManager</text>
</svg>
`
  }
  return `${NOTE(label)}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 208 40" width="208" height="40"
     role="img" aria-label="RepoManager">
  <g transform="translate(2 4) scale(1)">
  ${markBody('display', structure, COLOR.lime)}
  </g>
  <text x="44" y="27"
        font-family="Archivo, 'Archivo Variable', ui-sans-serif, system-ui, sans-serif"
        font-size="22" font-weight="700" letter-spacing="-0.6" fill="${structure}">RepoManager</text>
</svg>
`
}

// ── The kit ───────────────────────────────────────────────────────────────
export const ASSETS = {
  // Bare marks — for UI, docs and anywhere the ground is already known.
  'brand/mark-display.svg': mark({ label: 'display cut, for light grounds' }),
  'brand/mark-display-inverse.svg': mark({ structure: COLOR.paper, label: 'display cut, for dark grounds' }),
  'brand/mark-small.svg': mark({ cut: 'small', label: 'small cut, 24 px and below' }),
  'brand/mark-small-inverse.svg': mark({ cut: 'small', structure: COLOR.paper, label: 'small cut for dark grounds' }),
  // One colour: structure AND node collapse to currentColor, so a themed host
  // or a one-colour print keeps the silhouette intact.
  'brand/mark-mono.svg': mark({ structure: 'currentColor', accent: 'currentColor', label: 'single colour' }),

  // Lockups.
  'brand/lockup-horizontal.svg': lockup({}),
  'brand/lockup-horizontal-inverse.svg': lockup({ structure: COLOR.paper }),
  'brand/lockup-stacked.svg': lockup({ stacked: true }),

  // Installed-application tiles — one per shape language.
  // markScale differs per platform on purpose — see the note in tile().
  'brand/tile-macos.svg': tile({ size: 1024, art: 824, radius: 185.4, markScale: 0.68, label: 'macOS tile (824 art in a 1024 canvas, pre-rounded)' }),
  'brand/tile-windows.svg': tile({ size: 256, art: 256, radius: 30, markScale: 0.72, label: 'Windows tile' }),
  // 0.58: an adaptive icon is masked to a circle inscribed in the square, and
  // Android's own safe zone is tighter still (66 of 108dp). Anything larger
  // loses the rail's caps to the mask.
  'brand/tile-adaptive.svg': tile({ size: 512, art: 512, radius: 256, markScale: 0.58, label: 'adaptive / circular crop' }),

  // Favicon: a tile, because browser chrome is light in one theme and dark in
  // the other and a bare mark would vanish into one of them.
  //
  // SMALL cut, deliberately. A browser tab is 16 CSS px and that is where this
  // file spends its life — the display cut's ring closes into a smudge there.
  // Larger surfaces (apple-touch, OG card) get the display cut from the tiles
  // above, which is the entire point of having two cuts.
  'public/logo.svg': tile({ size: 64, art: 64, radius: 14, cut: 'small', markScale: 0.78, label: 'favicon / app mark' }),
}

function write() {
  for (const [rel, content] of Object.entries(ASSETS)) {
    const abs = path.join(ROOT, rel)
    fs.mkdirSync(path.dirname(abs), { recursive: true })
    fs.writeFileSync(abs, content)
  }
  console.log(`Wrote ${Object.keys(ASSETS).length} brand assets.`)
}

function check() {
  const drifted = []
  for (const [rel, content] of Object.entries(ASSETS)) {
    const abs = path.join(ROOT, rel)
    if (!fs.existsSync(abs)) { drifted.push(`${rel} (missing)`); continue }
    if (fs.readFileSync(abs, 'utf8') !== content) drifted.push(`${rel} (differs)`)
  }
  if (drifted.length) {
    console.error('Brand assets are out of sync with scripts/gen-brand.mjs:')
    for (const d of drifted) console.error(`  ${d}`)
    console.error('\nRun: node scripts/gen-brand.mjs')
    process.exit(1)
  }
  console.log(`brand: ${Object.keys(ASSETS).length} assets match the generator.`)
}

// pathToFileURL, not a hand-built file:// string — argv[1] is a `D:\…` path on
// Windows and the naive form silently fails to match there.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.argv.includes('--check') ? check() : write()
}
