// GENERATED by scripts/gen-brand.mjs — do not edit by hand.
// Change the geometry in that script and run `npm run gen:brand`.
// Spec: docs/BRAND.md

const DISPLAY_CUT = (
    <>
        <g fill="none" stroke="var(--brand-structure, currentColor)" strokeWidth="2.9" strokeLinecap="round">
        <path d="M5.8 5.6 V26.4"/><path d="M5.8 16 H14.4"/>
        </g>
        <circle cx="5.8" cy="5.6" r="2.1" fill="var(--brand-structure, currentColor)"/>
        <circle cx="5.8" cy="26.4" r="2.1" fill="var(--brand-structure, currentColor)"/>
        <circle cx="20.3" cy="16" r="4.7" fill="var(--brand-node, #7fc528)"/>
        <circle cx="20.3" cy="16" r="7.6" fill="none" stroke="var(--brand-node, #7fc528)" strokeWidth="1.9" opacity="0.45"/>
    </>
)

const SMALL_CUT = (
    <>
        <g fill="none" stroke="var(--brand-structure, currentColor)" strokeWidth="3.8" strokeLinecap="round">
        <path d="M6.5 6.5 V25.5"/><path d="M6.5 16 H13.5"/>
        </g>
        <circle cx="21" cy="16" r="6.2" fill="var(--brand-node, #7fc528)"/>
    </>
)

/** The size at or above which the display cut is used. */
export const CUT_BOUNDARY = 25

/**
 * The RepoManager mark.
 *
 * Two optical cuts, chosen by `size` rather than by the caller: below
 * 25 px the ring closes into a smudge and the 2.9 stroke lands between
 * pixels, so the small cut is a redraw — ring dropped, node grown, strokes
 * thickened. Passing the display cut to a 16 px slot is the one mistake this
 * whole system exists to prevent, which is why it is not a prop.
 *
 * The node is the only carrier of brand recognition. Do not recolour it.
 *
 * @param {number} size   Rendered size in CSS pixels; also picks the cut.
 * @param {string} title  Accessible name; pass '' for a decorative mark.
 */
export function BrandMark({ size = 32, className = '', title = 'RepoManager', ...rest }) {
    return (
        <svg
            viewBox="0 0 32 32"
            width={size}
            height={size}
            className={className}
            role="img"
            aria-label={title || undefined}
            aria-hidden={title ? undefined : true}
            {...rest}
        >
            {size < CUT_BOUNDARY ? SMALL_CUT : DISPLAY_CUT}
        </svg>
    )
}
